// src/solid/ssr.ts
import {
  Accessor,
  createContext,
  createEffect,
  createMemo,
  useContext,
} from 'solid-js'
import {Domain, is, Scope, scopeBind, Store} from 'effector'
import {throwError} from './lib/throw'
import {useStoreBase, useStoreMapBase} from './lib/base'
import {useGate as commonUseGate, createGateImplementation} from './lib/gate'
import type {Gate} from './index.h'

const ScopeContext = createContext<Scope | null>(null)
export const {Provider} = ScopeContext

function getScope() {
  const scope = useContext(ScopeContext)
  if (!scope)
    throwError('No scope found, consider adding <Provider> to app root')
  return scope as Scope
}

export function createGate<Props>(
  config: {
    domain?: Domain
    defaultState?: Props
    name?: string
  } = {},
) {
  return createGateImplementation({
    domain: config.domain,
    name: config.name,
    defaultState: 'defaultState' in config ? config.defaultState : {},
    hook: useGate,
  })
}

export function useGate<Props>(
  GateComponent: Gate<Props>,
  props: Accessor<Props> = () => ({} as any),
) {
  const events = useEvent([
    GateComponent.open,
    GateComponent.close,
    GateComponent.set,
  ])

  const ForkedGate = createMemo(() => {
    const [open, close, set] = events()

    return {
      open,
      close,
      set,
    } as Gate<Props>
  })

  createEffect(() => commonUseGate(ForkedGate(), props))
}

/** useStore wrapper for scopes */
export function useStore<T>(store: Store<T>): Accessor<T> {
  return useStoreBase(store, getScope())
}
/** useStoreMap wrapper for scopes */
export function useStoreMap(configOrStore: any, separateFn: any) {
  const scope = getScope()
  if (separateFn) return useStoreMapBase([configOrStore, separateFn], scope)
  return useStoreMapBase(
    [
      {
        store: configOrStore.store,
        keys: configOrStore.keys,
        fn: configOrStore.fn,
        updateFilter: configOrStore.updateFilter,
      },
    ],
    scope,
  )
}
/**
 bind event to scope
 */
export function useEvent(eventObject: any) {
  const scope = getScope()

  if (is.unit(eventObject)) {
    //@ts-expect-error
    return scopeBind(eventObject, {scope})
  }
  const shape = Array.isArray(eventObject) ? [] : ({} as any)
  for (const key in eventObject) {
    shape[key] = scopeBind(eventObject[key], {scope})
  }
  return shape
}

// src/react/ssr.ts
import React from 'react'
import {Domain, is, Scope, Store, scopeBind} from 'effector'
import {useStoreBase, useStoreMapBase, useListBase} from './apiBase'
import {withDisplayName} from './withDisplayName'
import {useGate as commonUseGate, createGateImplementation} from './createGate'
import type {Gate} from './index.h'
import {throwError} from './throw'
import {deprecate} from './deprecate'
import {processArgsToConfig} from '../effector/config'

const ScopeContext = React.createContext(null as Scope | null)
export const {Provider} = ScopeContext
function getScope() {
  const scope = React.useContext(ScopeContext)
  if (!scope)
    throwError('No scope found, consider adding <Provider> to app root')
  return scope as Scope
}

export function createGate<Props>(
  ...args: Array<
    | {
        domain?: Domain
        defaultState?: Props
        name?: string
      }
    | {}
  >
) {
  const [[config], metadata] = processArgsToConfig(args)
  return createGateImplementation({
    domain: config.domain,
    defaultState: 'defaultState' in config ? config.defaultState : {},
    hook: useGate,
    mainConfig: config,
    maybeConfig: metadata,
  })
}

export function useGate<Props>(
  GateComponent: Gate<Props>,
  props: Props = {} as any,
) {
  const [open, close, set] = useEvent([
    GateComponent.open,
    GateComponent.close,
    GateComponent.set,
  ])
  const ForkedGate = React.useMemo(
    () =>
      ({
        open,
        close,
        set,
      } as Gate<Props>),
    [GateComponent, open],
  )
  commonUseGate(ForkedGate, props)
}

export function createStoreConsumer(store: any) {
  return (props: any) => {
    const state = useStore(store)
    return props.children(state)
  }
}

export const createContextComponent = (
  store: any,
  context: any,
  renderProp: any,
) => {
  deprecate('createContextComponent')
  return (props: any) => {
    const ctx = React.useContext(context)
    const state = useStore(store)
    return renderProp(props, state, ctx)
  }
}

export const createComponent = (shape: any) => throwError('not implemented')

export const createReactState = (store: any, Component: any) => {
  deprecate('createReactState')
  return connect(Component)(store)
}

export const connect = (Component: any) => (store: any) => {
  let View: any = Component
  if (typeof Component !== 'function') {
    View = store
    store = Component as any
  }
  const wrappedComponentName = View.displayName || View.name || 'Unknown'
  return withDisplayName(`Connect(${wrappedComponentName})`, (props: any) =>
    React.createElement(View, {...props, ...(useStore(store) as any)}),
  )
}

/** useStore wrapper for scopes */
export function useStore<T>(store: Store<T>): T {
  return useStoreBase(store, getScope())
}
/** useList wrapper for scopes */
export function useList(store: any, opts: any) {
  return useListBase(store, opts, getScope())
}
/** useStoreMap wrapper for scopes */
export function useStoreMap(configOrStore: any, separateFn: any) {
  const scope = getScope()
  if (separateFn) return useStoreMapBase([configOrStore, separateFn], scope)
  return useStoreMapBase(
    [
      {
        store: configOrStore.store,
        keys: configOrStore.keys,
        fn: configOrStore.fn,
        updateFilter: configOrStore.updateFilter,
      },
    ],
    scope,
  )
}

/**
bind event to scope

works like React.useCallback, but for scopes
*/
export function useEvent(eventObject: any) {
  const scope = getScope()
  const isShape = !is.unit(eventObject) && typeof eventObject === 'object'
  const events = isShape ? eventObject : {event: eventObject}

  return React.useMemo(() => {
    if (is.unit(eventObject)) {
      //@ts-expect-error
      return scopeBind(eventObject, {scope})
    }
    const shape = Array.isArray(eventObject) ? [] : ({} as any)
    for (const key in eventObject) {
      shape[key] = scopeBind(eventObject[key], {scope})
    }
    return shape
  }, [scope, ...Object.keys(events), ...Object.values(events)])
}
